DROP TABLE USERS;
CREATE TABLE USERS(
	USERID VARCHAR2(20) PRIMARY KEY,
	USERNAME VARCHAR2(20),
	GENDER VARCHAR2(10),
	ADDRESS VARCHAR2(20)
);
INSERT INTO USERS VALUES('USER1' ,'에밀리','여','서울');
INSERT INTO USERS VALUES('USER2' ,'사만다','여','경기');
INSERT INTO USERS VALUES('USER3' ,'데이빗','남','인천');
INSERT INTO USERS VALUES('USER4' ,'제임스','남','부산');
INSERT INTO USERS VALUES('USER5' ,'브라운','남','제주');