DROP SEQUENCE FAQBOARDS_SEQ;
DROP SEQUENCE ORDERS_SEQ;
DROP SEQUENCE CART_SEQ;
DROP SEQUENCE REVIEWS_SEQ;
DROP SEQUENCE PRODUCTS_SEQ;
DROP SEQUENCE MEMBERS_SEQ;

DROP TABLE FAQBOARDS;
DROP TABLE ORDERS;
DROP TABLE CART;
DROP TABLE REVIEWS;
DROP TABLE PRODUCTS;
DROP TABLE MEMBERS;



CREATE TABLE MEMBERS ( -- 회원 테이블
    MNO NUMBER PRIMARY KEY, --  회원번호
    MSNO VARCHAR2(14) NOT NULL UNIQUE, -- 회원주민등록번호
      MID VARCHAR2(50) NOT NULL UNIQUE, -- 회원 ID
    MNAME VARCHAR2(50) NOT NULL, -- 회원이름
    MPW VARCHAR2(50) NOT NULL, -- 회원 PW
    MADDR VARCHAR2(1000) NOT NULL, -- 회원 주소
    MPNO (5) , -- 회원 우편번호
    MEMAIL VARCHAR2(100) NOT NULL, -- 회원 이메일
    MPHONE VARCHAR2(20) NOT NULL, -- 회원 전화번호
    MPAYMENT NUMBER, -- 회원 결제방법코드
    MPOINT NUMBER, -- 구매포인트
    MGRADE CHAR(1), -- 회원등급
    MREGDATE DATE -- 가입일
);

CREATE SEQUENCE MEMBERS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE
NOCACHE;



CREATE TABLE PRODUCTS( -- 상품 테이블
    PNO NUMBER PRIMARY KEY, -- 상품 번호
    PNAME VARCHAR2(100) NOT NULL, -- 상품명
    PFILENAME VARCHAR2(100), -- 상품 이미지
    PPRICE NUMBER NOT NULL, -- 상품 가격(단가)
    PCATEGORY VARCHAR2(100), -- 상품 구분(카테고리)
    PCATEGORY_SUB VARCHAR2(100), -- 상품 구분(카테고리) 소분류
    PBRAND VARCHAR2(100) NOT NULL ,-- 판매자 상호
    PDISRATE NUMBER, -- 상품 할인율
    PSIZE VARCHAR2(100)  --상품 사이즈

);

CREATE SEQUENCE PRODUCTS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE
NOCACHE;


CREATE TABLE ORDERS( -- 주문 테이블
    ONO NUMBER PRIMARY KEY, -- 주문 번호
    MNO NUMBER NOT NULL REFERENCES MEMBERS (MNO), -- 주문 회원 ID(외래키)
    PNO NUMBER NOT NULL REFERENCES PRODUCTS (PNO), -- 상품 번호(외래키)
    OAMOUNT NUMBER NOT NULL, -- 주문 수량
    ODATE DATE, -- 주문 일자
    OADDR VARCHAR2(300) NOT NULL, -- 배송지 주소
    OPHONE VARCHAR2(20) NOT NULL, -- 배송지 전화번호
    OPAYMENT NUMBER NOT NULL, -- 결제 방법
    ONOTE VARCHAR2(500) -- 기타 메모
);

CREATE SEQUENCE ORDERS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE
NOCACHE;


CREATE TABLE CART( -- 장바구니 테이블
    CNO NUMBER PRIMARY KEY, -- 장바구니 번호
    MID VARCHAR2(50) NOT NULL REFERENCES MEMBERS (MID), -- 회원 ID(외래키)
    PNO NUMBER NOT NULL REFERENCES PRODUCTS (PNO), -- 상품 번호(외래키)
    CAMOUNT NUMBER NOT NULL -- 상품 수량
);


CREATE SEQUENCE CART_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE
NOCACHE;

CREATE TABLE FAQBOARDS( -- FAQ 테이블
    FAQNO NUMBER PRIMARY KEY, -- FAQ 번호
    MID VARCHAR2(50) NOT NULL REFERENCES MEMBERS (MID), -- 회원 ID(외래키)
    FAQREGDATE DATE, -- FAQ 작성일
    FAQTITLE VARCHAR2(100) NOT NULL, -- FAQ 제목
    FAQCONTENT VARCHAR2(2000), -- FAQ 내용
    FAQHIT NUMBER, -- 조회수
    FAQPW VARCHAR2(20) NOT NULL, -- 게시글 PW (삭제용)
    FAQSTEP NUMBER, --
    FAQDEPTH NUMBER ,--
    FAQCLASS NUMBER
);


CREATE SEQUENCE FAQBOARDS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE
NOCACHE;


CREATE TABLE REVIEWS( -- 리뷰 테이블
    RNO NUMBER PRIMARY KEY, -- 리뷰 번호
    PNO NUMBER NOT NULL REFERENCES PRODUCTS (PNO), -- 상품 번호(외래키)
    MID VARCHAR2(50) NOT NULL REFERENCES MEMBERS (MID), -- 작성자 : 회원 ID(외래키)
    RCONTENT VARCHAR2(1000) NOT NULL, -- 리뷰 내용
    RFILENAME VARCHAR2(100), -- 리뷰 이미지 파일 이름
    RPW VARCHAR2(20) NOT NULL, -- 리뷰
    RREGDATE DATE, -- 리뷰 작성일
    RLIKES NUMBER ,-- 좋아요 수
    RRATING NUMBER --고객이남기는 평점
);


CREATE SEQUENCE REVIEWS_SEQ
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCYCLE
NOCACHE;
/*

MNO MSNO MID MNAME MPW MADDR MPNO MEMAIL MPHONE MPAYMENT MPOINT MGRADE MREGDATE
회원번호 주민 회원아이디 이름 비번 주소 우편번호 이메일 전화번호 결제방법 구매포인트 회원등급 가입일
 */
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'111111-1111111','ADMIN','관리자','1111','서울 청담',14506,'ADMIN@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'211111-1111111','USER1','1사용자','1111','부산',14506,'USER1@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'311111-1111111','USER2','2사용자','1111','대구 마포',14506,'USER2@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'411111-1111111','USER3','3사용자','1111','제주 마포',14506,'USER3@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'511111-1111111','USER4','4사용자','1111','경기 부천 마포',21551,'USER4@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'611111-1111111','USER5','5사용자','1111','경기 시흥',14056,'USER5@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'711111-1111111','USER6','6사용자','1111','강원 강릉',23456,'USER6@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'811111-1111111','USER7','7사용자','1111','충남 대전',24717,'USER7@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'911111-1111111','USER8','8사용자','1111','해남',12735,'USER8@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'101111-1111111','USER9','9사용자','1111','전남 목포',26237,'USER9@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
INSERT INTO MEMBERS VALUES (MEMBERS_SEQ.nextval,'201111-1111111','USER10','10사용자','1111','독도',35070,'USER410@EMAIL.COM','010-0000-0000',NULL,NULL,NULL,SYSDATE);
COMMIT;

/* 상품번호 ,상품명, 상품이미지 ,상품가격 ,상품구분, 상품 소분류 상품 ,브랜드,할인율, 사이즈
*/
/*상의 티셔츠  나이키*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '드라이 스우시 반팔','드라이_스우시_반팔.jpg', 59000, '상의', '티셔츠', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 'NSW 퓨추라반팔','NSW_퓨추라반팔.jpg', 59000, '상의', '티셔츠', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '프로타이트 깁팔','프로타이트_깁팔.jpg', 35000, '상의', '티셔츠', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 'NSW 스우시 반팔','NSW_스우시_반팔.jpg', 49000, '상의', '티셔츠', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 'NSW 스우시 반팔','NSW_스우시_반팔.jpg', 32000, '상의', '티셔츠', '나이키', 0,NULL);
COMMIT;


/*상의 티셔츠 아디다스*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '락업티','락업티.jpg', 23000, '상의', '티셔츠', '아디다스', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '아디컬러프리머엄티셔츠','아디컬러프리머엄티셔츠.jpg', 23000, '상의', '티셔츠', '아디다스', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 'MTEC티셔츠네이비','MTEC티셔츠네이비.jpg', 23000, '상의', '티셔츠', '아디다스', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 'MTEC티셔츠카키','MTEC티셔츠.jpg', 23000, '상의', '티셔츠', '아디다스', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '파스텔티셔츠','파스텔티셔츠.jpg', 23000, '상의', '티셔츠', '아디다스', 0,NULL);
COMMIT;
/*상의 맨투맨후드 나이키*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '브러스트클럽맨투맨','브러스트클럽맨투맨.jpg', 69000, '상의', '맨투맨후드', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 'NSW퓨추라크루탑','NSW퓨추라크루탑.jpg', 89000, '상의', '맨투맨후드', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 'NSW에어플리스크루넥','NSW에어플리스크루넥.jpg', 59000, '상의', '맨투맨후드', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '미들체리후드','미들체리후드.jpg', 78000, '상의', '맨투맨후드', '나이키', 0,NULL);
COMMIT;

/*상의 맨투맨후드 아디다스*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '릴렉스오버사이즈크루넥','릴렉스오버사이즈크루넥.jpg', 78000, '상의', '맨투맨후드', '아디다스', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 'WUPO스웻셔츠블랙','WUPO스웻셔츠블랙.jpg', 59000, '상의', '맨투맨후드', '아디다스', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '3ST크루블루','3ST크루블루.jpg', 59000, '상의', '맨투맨후드', '아디다스', 0,NULL);
COMMIT;

/*하의 청바지 페이탈리즘*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '무파진블루','무파진블루.jpg', 59000, '하의', '청바지', '페이탈리즘', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '크롭진블루','크롭진블루.jpg', 59000, '하의', '청바지', '페이탈리즘', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '샌드크림진','샌드크림진.jpg', 59000, '하의', '청바지', '페이탈리즘', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '타이핏크롭진','타이핏크롭진.jpg', 59000, '하의', '청바지', '페이탈리즘', 0,NULL);
COMMIT;
/*하의 청바지 피스워커*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '가먼트진','가먼트진.jpg', 59000, '하의', '청바지', '피스워커', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '마인워커','마인워커.jpg', 59000, '하의', '청바지', '피스워커', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '라이트크롭','라이트크롭.jpg', 59000, '하의', '청바지', '피스워커', 0,NULL);
COMMIT;
/*하의 슬랙스 페이탈리즘*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '롱와이드슬랙스','롱와이드슬랙스.jpg', 59000, '하의', '슬랙스', '페이탈리즘', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '스트레이트앞트임슬랙스','스트레이트앞트임슬랙스.jpg', 59000, '하의', '슬랙스', '페이탈리즘', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '옆트임슬랙스','옆트임슬랙스.jpg', 59000, '하의', '슬랙스', '페이탈리즘', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '크롭핏절개슬랙스','크롭핏절개슬랙스.jpg', 59000, '하의', '슬랙스', '페이탈리즘', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '조거핏슬랙스','조거핏슬랙스.jpg', 59000, '하의', '슬랙스', '페이탈리즘', 0,NULL);
COMMIT;
/*하의 슬랙스 피스워커*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '밴딩슬랙스','밴딩슬랙스.jpg', 59000, '하의', '슬랙스', '피스워커', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '코튼린넨슬랙스','코튼린넨슬랙스.jpg', 59000, '하의', '슬랙스', '피스워커', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '밴딩플리츠슬랙스','밴딩플리츠슬랙스.jpg', 59000, '하의', '슬랙스', '피스워커', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '유니섹스세미와이드','유니섹스세미와이드.jpg', 59000, '하의', '슬랙스', '피스워커', 0,NULL);
COMMIT;

/*아우터 자켓 나이키*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '아카데미바람막이자켓','아카데미바람막이자켓.jpg', 99000, '아우터', '자켓', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 'NSW스우시윈드러너자켓','NSW스우시윈드러너자켓.jpg', 129000, '아우터', '자켓', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '우븐하프아노락','우븐하프아노락.jpg', 129000, '아우터', '자켓', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '스우시트랙자켓','스우시트랙자켓.jpg', 129000, '아우터', '자켓', '나이키', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '우먼스우븐자켓','우먼스우븐자켓.jpg', 149000, '아우터', '자켓', '나이키', 0,NULL);
COMMIT;
/*아우터 자켓 아디다스*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '락업윈드브레이커','락업윈드브레이커.jpg', 99000, '아우터', '자켓', '아디다스', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '파스텔트랙탑','파스텔트랙탑.jpg', 99000, '아우터', '자켓', '아디다스', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, 'AI윈드브레이커클래식','AI윈드브레이커클래식.jpg', 99000, '아우터', '자켓', '아디다스', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '락업트랙탑화이트','락업트랙탑화이트.jpg', 89000, '아우터', '자켓', '아디다스', 0,NULL);
COMMIT;

/*아우터 코트 페이탈리즘*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '라이트롱트렌치코트','라이트롱트렌치코트.jpg', 179000, '아우터', '코트', '페이탈리즘', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '트로피컬울마칸코트','트로피컬울마칸코트.jpg', 219000, '아우터', '코트', '페이탈리즘', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '보야드싱글코트','보야드싱글코트.jpg', 179000, '아우터', '코트', '페이탈리즘', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '후드코트','후드코트.jpg', 249000, '아우터', '코트', '페이탈리즘', 0,NULL);
COMMIT;

/*아우터 코트 피스워커*/
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '오버사이즈트렌치','오버사이즈트렌치.jpg', 179000, '아우터', '코트', '피스워커', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '모던체크오버트렌치','모던체크오버트렌치.jpg', 179000, '아우터', '코트', '피스워커', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '쉐이드체크오버트렌치','쉐이드체크오버트렌치.jpg', 179000, '아우터', '코트', '피스워커', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '오버사이즈트렌치그래이','오버사이즈트렌치그래이.jpg', 179000, '아우터', '코트', '피스워커', 0,NULL);
INSERT INTO PRODUCTS VALUES (PRODUCTS_SEQ.NEXTVAL, '울코트트렌치','울코트트렌치.jpg', 219000, '아우터', '코트', '피스워커', 0,NULL);
COMMIT;












SELECT MEMBERS_SEQ.currval FROM DUAL;

/*주문페이지에서 마이바티스이용시 2,3,4번째컬럼을 변수처리해서 이용하면될듯합니다.
  부천시상동 010-1111-1234 저부분도 주문페이지에서 변수처리해서 사용자가입력받은데이터를 삽입하여 이용하면될듯합니다.
  */
  /*주문번호,주문회원번호(외래키),상품번호(외래키),주문수량,주문일자,배송지주소,배송지전화번호,결제방법,기타메모*/
INSERT INTO ORDERS VALUES (ORDERS_SEQ.nextval,3,1,1,SYSDATE,'경기도 부천시 상동','010-1111-1234',1,NULL);
INSERT INTO ORDERS VALUES (ORDERS_SEQ.nextval,4,2,1,SYSDATE,'경기도 부천시 상동','010-1111-1234',1,NULL);
INSERT INTO ORDERS VALUES (ORDERS_SEQ.nextval,1,1,1,SYSDATE,'경기도 부천시 상동','010-1111-1234',1,NULL);
INSERT INTO ORDERS VALUES (ORDERS_SEQ.nextval,10,1,1,SYSDATE,'경기도 부천시 상동','010-1111-1234',1,NULL);
INSERT INTO ORDERS VALUES (ORDERS_SEQ.nextval,10,1,1,SYSDATE,'경기도 부천시 상동','010-1111-1234',1,NULL);

COMMIT

INSERT INTO ORDERS VALUES (ORDERS_SEQ.nextval,1,1,1,'2020-06-07','경기도 부천시 상동','010-1111-1234',1,NULL);
INSERT INTO ORDERS VALUES (ORDERS_SEQ.nextval,6,1,1,'2020-06-17','경기도 부천시 상동','010-1111-1234',1,NULL);
INSERT INTO ORDERS VALUES (ORDERS_SEQ.nextval,7,1,1,'2020-05-07','경기도 부천시 상동','010-1111-1234',1,NULL);

INSERT INTO ORDERS VALUES (ORDERS_SEQ.nextval,2,1,1,'2020-06-17','경기도 부천시 상동','010-1111-1234',1,NULL);
INSERT INTO ORDERS VALUES (ORDERS_SEQ.nextval,2,1,1,'2020-05-07','경기도 부천시 상동','010-1111-1234',1,NULL);
COMMIT